[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

# Use Ubuntu 24.04 Noble instead of deprecated Focal
[build.image]
  ubuntu = "24.04"

[context.production.environment]
  NODE_ENV = "production"
  ELEVENTY_ENV = "production"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

[[redirects]]
  from = "/services"
  to = "/work/services"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/work"
  status = 301
